#include <iostream>
#include <string>
#include <vector>
#include <libconfig.h++>
#include "../Math/Point3D.hpp"
#include "Objects/Shapes/Sphere.hpp"
#include "Objects/Shapes/Cone.hpp"
#include "Objects/Shapes/Plane.hpp"
#include "Objects/Shapes/Cylinder.hpp"
#include <type_traits>
#include <cstdint>
#include "Shape/FShape.hpp"
#include "PCamera.hpp"
#include "Light/DirectionalLight.hpp"
#include "Light/AmbientLight.hpp"
#include "Materials/Material.hpp"
#include "Materials/Mate.hpp"
#include "Materials/Metal.hpp"
